-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.addresses (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  profile_id uuid NOT NULL,
  address_type character varying NOT NULL,
  flat_no character varying,
  building character varying,
  street character varying,
  area character varying,
  city character varying,
  state character varying,
  pincode character varying,
  latitude numeric,
  longitude numeric,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  landmark character varying,
  taluk character varying,
  district character varying,
  country character varying,
  CONSTRAINT addresses_pkey PRIMARY KEY (id),
  CONSTRAINT addresses_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.economic_details (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  profile_id uuid NOT NULL UNIQUE,
  self_income USER-DEFINED,
  family_income USER-DEFINED,
  inv_fixed_deposits boolean DEFAULT false,
  inv_mutual_funds_sip boolean DEFAULT false,
  inv_shares_demat boolean DEFAULT false,
  inv_others boolean DEFAULT false,
  fac_rented_house boolean DEFAULT false,
  fac_own_house boolean DEFAULT false,
  fac_agricultural_land boolean DEFAULT false,
  fac_two_wheeler boolean DEFAULT false,
  fac_car boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT economic_details_pkey PRIMARY KEY (id),
  CONSTRAINT economic_details_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.family_history (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  profile_id uuid NOT NULL UNIQUE,
  ancestral_challenge_notes text,
  demigods_info text,
  snake_god_naga_info text,
  common_relative_names text,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT family_history_pkey PRIMARY KEY (id),
  CONSTRAINT family_history_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.family_info (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  profile_id uuid NOT NULL UNIQUE,
  family_type USER-DEFINED,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT family_info_pkey PRIMARY KEY (id),
  CONSTRAINT family_info_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.family_members (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  profile_id uuid NOT NULL,
  family_info_id uuid NOT NULL,
  relation character varying,
  name character varying,
  age smallint,
  dob date,
  disability character varying DEFAULT 'no'::character varying,
  gender USER-DEFINED,
  photo_url text,
  status USER-DEFINED DEFAULT 'active'::member_status,
  sort_order smallint DEFAULT 0,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT family_members_pkey PRIMARY KEY (id),
  CONSTRAINT family_members_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id),
  CONSTRAINT family_members_family_info_id_fkey FOREIGN KEY (family_info_id) REFERENCES public.family_info(id)
);
CREATE TABLE public.member_certifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  member_education_id uuid NOT NULL,
  certification character varying NOT NULL,
  sort_order smallint DEFAULT 0,
  CONSTRAINT member_certifications_pkey PRIMARY KEY (id),
  CONSTRAINT member_certifications_member_education_id_fkey FOREIGN KEY (member_education_id) REFERENCES public.member_education(id)
);
CREATE TABLE public.member_documents (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  profile_id uuid NOT NULL,
  member_name character varying,
  member_relation character varying,
  sort_order smallint DEFAULT 0,
  aadhaar_coverage USER-DEFINED,
  pan_coverage USER-DEFINED,
  voter_id_coverage USER-DEFINED,
  land_doc_coverage USER-DEFINED,
  dl_coverage USER-DEFINED,
  CONSTRAINT member_documents_pkey PRIMARY KEY (id),
  CONSTRAINT member_documents_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.member_education (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  profile_id uuid NOT NULL,
  member_name character varying,
  member_relation character varying,
  sort_order smallint DEFAULT 0,
  highest_education character varying,
  brief_profile text,
  profession_type USER-DEFINED,
  profession_other character varying,
  self_employed_type USER-DEFINED,
  self_employed_other character varying,
  industry character varying,
  is_currently_studying boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  is_currently_working boolean,
  CONSTRAINT member_education_pkey PRIMARY KEY (id),
  CONSTRAINT member_education_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.member_educations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  member_education_id uuid NOT NULL,
  degree_name text,
  degree_type text,
  university text,
  start_date date,
  end_date date,
  certificate text,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT member_educations_pkey PRIMARY KEY (id),
  CONSTRAINT member_educations_member_education_id_fkey FOREIGN KEY (member_education_id) REFERENCES public.member_education(id)
);
CREATE TABLE public.member_insurance (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  profile_id uuid NOT NULL,
  member_name character varying,
  member_relation character varying,
  sort_order smallint DEFAULT 0,
  health_coverage ARRAY,
  life_coverage ARRAY,
  term_coverage ARRAY,
  konkani_card_coverage ARRAY,
  CONSTRAINT member_insurance_pkey PRIMARY KEY (id),
  CONSTRAINT member_insurance_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.member_languages (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  member_education_id uuid NOT NULL,
  language character varying NOT NULL,
  language_other character varying,
  CONSTRAINT member_languages_pkey PRIMARY KEY (id),
  CONSTRAINT member_languages_member_education_id_fkey FOREIGN KEY (member_education_id) REFERENCES public.member_education(id)
);
CREATE TABLE public.member_sanghas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL,
  sangha_id uuid NOT NULL,
  sangha_name text,
  role text,
  tenure text,
  status text DEFAULT 'pending'::text,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT member_sanghas_pkey PRIMARY KEY (id),
  CONSTRAINT member_sanghas_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id),
  CONSTRAINT member_sanghas_sangha_id_fkey FOREIGN KEY (sangha_id) REFERENCES public.sanghas(id)
);
CREATE TABLE public.personal_details (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  profile_id uuid NOT NULL UNIQUE,
  first_name character varying NOT NULL,
  middle_name character varying,
  last_name character varying NOT NULL,
  gender USER-DEFINED NOT NULL,
  date_of_birth date,
  fathers_name character varying,
  mothers_name character varying,
  mothers_maiden_name character varying,
  wife_name character varying,
  wife_maiden_name character varying,
  husbands_name character varying,
  surname_in_use character varying,
  surname_as_per_gotra character varying,
  has_disability character varying,
  is_part_of_sangha character varying,
  sangha_name character varying,
  sangha_tenure character varying,
  sangha_role character varying,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  marital_status character varying,
  CONSTRAINT personal_details_pkey PRIMARY KEY (id),
  CONSTRAINT personal_details_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.profile_edit_requests (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  profile_id uuid NOT NULL,
  requested_by uuid NOT NULL,
  reason text,
  status character varying DEFAULT 'pending'::character varying,
  reviewed_by uuid,
  reviewed_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT profile_edit_requests_pkey PRIMARY KEY (id),
  CONSTRAINT profile_edit_requests_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id),
  CONSTRAINT profile_edit_requests_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES public.users(id),
  CONSTRAINT profile_edit_requests_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.users(id)
);
CREATE TABLE public.profile_review_history (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  profile_id uuid NOT NULL,
  action USER-DEFINED NOT NULL,
  performed_by uuid NOT NULL,
  comment text,
  snapshot jsonb,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT profile_review_history_pkey PRIMARY KEY (id),
  CONSTRAINT profile_review_history_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id),
  CONSTRAINT profile_review_history_performed_by_fkey FOREIGN KEY (performed_by) REFERENCES public.users(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  status USER-DEFINED NOT NULL DEFAULT 'draft'::profile_status,
  submitted_at timestamp without time zone,
  reviewed_at timestamp without time zone,
  reviewed_by uuid,
  review_comment text,
  sangha_id uuid,
  step1_personal_pct smallint DEFAULT 0,
  step2_religious_pct smallint DEFAULT 0,
  step3_family_pct smallint DEFAULT 0,
  step4_location_pct smallint DEFAULT 0,
  step5_education_pct smallint DEFAULT 0,
  step6_economic_pct smallint DEFAULT 0,
  overall_completion_pct smallint DEFAULT 0,
  step1_completed boolean DEFAULT false,
  step2_completed boolean DEFAULT false,
  step3_completed boolean DEFAULT false,
  step4_completed boolean DEFAULT false,
  step5_completed boolean DEFAULT false,
  step6_completed boolean DEFAULT false,
  photo_url text,
  photo_uploaded_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  step7_sangha_pct integer DEFAULT 0,
  step7_completed boolean DEFAULT false,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT profiles_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.users(id),
  CONSTRAINT profiles_sangha_id_fkey FOREIGN KEY (sangha_id) REFERENCES public.sanghas(id)
);
CREATE TABLE public.religious_details (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  profile_id uuid NOT NULL UNIQUE,
  gotra character varying,
  pravara character varying,
  kuladevata character varying,
  kuladevata_other character varying,
  surname_in_use character varying,
  surname_as_per_gotra character varying,
  priest_name character varying,
  priest_location character varying,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  upanama_general text,
  upanama_proper text,
  demi_god_challenge text,
  demi_gods ARRAY,
  demi_god_other text,
  ancestral_challenge character varying,
  ancestral_challenge_notes text,
  CONSTRAINT religious_details_pkey PRIMARY KEY (id),
  CONSTRAINT religious_details_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.sangha_members (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  sangha_id uuid NOT NULL,
  gender character varying,
  phone character varying,
  email character varying,
  dob date,
  role character varying,
  member_type character varying,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  first_name text NOT NULL,
  middle_name text,
  last_name text NOT NULL,
  CONSTRAINT sangha_members_pkey PRIMARY KEY (id),
  CONSTRAINT sangha_members_sangha_id_fkey FOREIGN KEY (sangha_id) REFERENCES public.sanghas(id)
);
CREATE TABLE public.sanghas (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  sangha_auth_id uuid NOT NULL UNIQUE,
  sangha_name text NOT NULL,
  logo_url text,
  address_line text,
  pincode character,
  village_town text,
  taluk text,
  district text,
  state text,
  email text,
  phone text,
  description text,
  sangha_contact_same boolean DEFAULT true,
  sangha_phone text,
  sangha_email text,
  status USER-DEFINED NOT NULL DEFAULT 'pending_approval'::sangha_status,
  rejection_reason text,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  is_blocked boolean DEFAULT false,
  address_line2 text,
  address_line3 text,
  city text,
  CONSTRAINT sanghas_pkey PRIMARY KEY (id),
  CONSTRAINT sanghas_sangha_auth_id_fkey FOREIGN KEY (sangha_auth_id) REFERENCES public.users(id)
);
CREATE TABLE public.scholarship_applications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  scholarship_id uuid NOT NULL,
  profile_id uuid NOT NULL,
  sangha_id uuid NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::scholarship_app_status,
  applied_at timestamp without time zone DEFAULT now(),
  reviewed_at timestamp without time zone,
  reviewed_by uuid,
  review_comment text,
  family_member_id uuid,
  checked_criteria jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT scholarship_applications_pkey PRIMARY KEY (id),
  CONSTRAINT scholarship_applications_scholarship_id_fkey FOREIGN KEY (scholarship_id) REFERENCES public.scholarships(id),
  CONSTRAINT scholarship_applications_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id),
  CONSTRAINT scholarship_applications_sangha_id_fkey FOREIGN KEY (sangha_id) REFERENCES public.sanghas(id),
  CONSTRAINT scholarship_applications_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.users(id),
  CONSTRAINT scholarship_applications_family_member_id_fkey FOREIGN KEY (family_member_id) REFERENCES public.family_members(id)
);
CREATE TABLE public.scholarship_categories (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  sangha_id uuid,
  name text NOT NULL,
  color text NOT NULL DEFAULT '#534AB7'::text,
  sort_order smallint NOT NULL DEFAULT 0,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT scholarship_categories_pkey PRIMARY KEY (id),
  CONSTRAINT scholarship_categories_sangha_id_fkey FOREIGN KEY (sangha_id) REFERENCES public.sanghas(id)
);
CREATE TABLE public.scholarship_eligibility_cache (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  profile_id uuid NOT NULL,
  scholarship_id uuid NOT NULL,
  is_eligible boolean DEFAULT false,
  reasons ARRAY DEFAULT '{}'::text[],
  calculated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT scholarship_eligibility_cache_pkey PRIMARY KEY (id),
  CONSTRAINT scholarship_eligibility_cache_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id),
  CONSTRAINT scholarship_eligibility_cache_scholarship_id_fkey FOREIGN KEY (scholarship_id) REFERENCES public.scholarships(id)
);
CREATE TABLE public.scholarship_tiers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  scholarship_id uuid NOT NULL,
  label text NOT NULL,
  amount numeric NOT NULL,
  condition_note text,
  sort_order smallint NOT NULL DEFAULT 0,
  CONSTRAINT scholarship_tiers_pkey PRIMARY KEY (id),
  CONSTRAINT scholarship_tiers_scholarship_id_fkey FOREIGN KEY (scholarship_id) REFERENCES public.scholarships(id)
);
CREATE TABLE public.scholarships (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  sangha_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  base_amount numeric,
  status USER-DEFINED NOT NULL DEFAULT 'draft'::scholarship_status,
  age_min smallint,
  age_max smallint,
  gender USER-DEFINED NOT NULL DEFAULT 'all'::gender_eligibility,
  disability_required boolean,
  marital_status USER-DEFINED NOT NULL DEFAULT 'all'::marital_eligibility,
  max_family_size smallint,
  max_dependents smallint,
  single_parent_only boolean,
  disabled_family_member boolean,
  family_type USER-DEFINED NOT NULL DEFAULT 'all'::family_type_eligibility,
  states ARRAY NOT NULL DEFAULT '{}'::text[],
  districts ARRAY NOT NULL DEFAULT '{}'::text[],
  education_levels ARRAY NOT NULL DEFAULT '{}'::text[],
  degrees ARRAY NOT NULL DEFAULT '{}'::text[],
  universities ARRAY NOT NULL DEFAULT '{}'::text[],
  merit_based boolean,
  currently_studying boolean,
  employment_status USER-DEFINED NOT NULL DEFAULT 'all'::employment_eligibility,
  annual_family_income_min numeric,
  annual_family_income_max numeric,
  self_income_min numeric,
  self_income_max numeric,
  ews_only boolean,
  house_ownership USER-DEFINED NOT NULL DEFAULT 'all'::house_ownership_eligibility,
  agricultural_family boolean,
  vehicle_ownership USER-DEFINED NOT NULL DEFAULT 'all'::vehicle_eligibility,
  has_assets boolean,
  has_investments boolean,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  category_id uuid,
  visibility USER-DEFINED NOT NULL DEFAULT 'primary_sangha_only'::scholarship_visibility,
  max_approvals_unlimited boolean NOT NULL DEFAULT true,
  max_approvals smallint,
  application_start date,
  application_end date,
  religion ARRAY NOT NULL DEFAULT '{}'::text[],
  caste ARRAY NOT NULL DEFAULT '{}'::text[],
  domicile boolean,
  orphan boolean,
  minority_community boolean,
  sports_quota boolean,
  rural_background boolean,
  cgpa_min numeric,
  percentage_min numeric,
  health_insurance boolean,
  life_insurance boolean,
  term_insurance boolean,
  aadhaar_card USER-DEFINED NOT NULL DEFAULT 'all'::doc_card_coverage,
  pan_card USER-DEFINED NOT NULL DEFAULT 'all'::doc_card_coverage,
  voter_id USER-DEFINED NOT NULL DEFAULT 'all'::doc_card_coverage,
  driving_license USER-DEFINED NOT NULL DEFAULT 'all'::doc_card_coverage,
  konkani_card boolean,
  land_documents boolean,
  fac_rented_house boolean,
  fac_own_house boolean,
  fac_agricultural_land boolean,
  fac_two_wheeler boolean,
  fac_car boolean,
  inv_fixed_deposits boolean,
  inv_mutual_funds_sip boolean,
  inv_shares_demat boolean,
  inv_others boolean,
  CONSTRAINT scholarships_pkey PRIMARY KEY (id),
  CONSTRAINT scholarships_sangha_id_fkey FOREIGN KEY (sangha_id) REFERENCES public.sanghas(id),
  CONSTRAINT scholarships_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.scholarship_categories(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  role USER-DEFINED NOT NULL DEFAULT 'user'::user_role,
  email character varying UNIQUE,
  phone character varying UNIQUE,
  password_hash text,
  otp_code character varying,
  otp_expires_at timestamp without time zone,
  is_phone_verified boolean DEFAULT false,
  is_email_verified boolean DEFAULT false,
  is_active boolean DEFAULT true,
  is_deleted boolean DEFAULT false,
  last_login_at timestamp without time zone,
  last_login_ip character varying,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  is_blocked boolean DEFAULT false,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);